import type { PlaceCategory } from '@/lib/categories';

export type WifiBucket = 'fast' | 'moderate' | 'slow' | 'unknown';
export type NoiseBucket = 'quiet' | 'moderate' | 'loud' | 'unknown';
export type OutletsBucket = 'many' | 'some' | 'none' | 'unknown';
export type SeatsBucket = 'plenty' | 'some' | 'full' | 'unknown';
export type LightingBucket = 'good' | 'dim' | 'unknown';

export interface DemoPlace {
  id: string;
  name: string;
  address: string;
  neighborhood: string;
  category: PlaceCategory;
  lat: number;
  lng: number;
  rating: number;
  review_count: number;
  avg_spend_eur: number;
  wifi: WifiBucket;
  noise: NoiseBucket;
  outlets: OutletsBucket;
  seats: SeatsBucket;
  lighting: LightingBucket;
  tabletime_hours: number;
  right_now_noise: string;
  right_now_seating: string;
  /** OSM `opening_hours` raw string when available (e.g. `Mo-Fr 09:00-18:00`). */
  hours_raw?: string | null;
  /** Set when the API found at least one `source='user'` review for this
   *  place. Used by the map page's filter logic to bypass the active
   *  category filter — reviewed places are "validated" and always show
   *  regardless of the curated default. See #77. */
  has_user_reviews?: boolean;
  /** Same fact as `has_user_reviews`, just exposed as a count for any UI
   *  that wants to render it ("3 reviews"). Optional. */
  user_review_count?: number;
  /** Optional brand string surfaced from the slim payload — used by the
   *  bbox map fetch path. Not present on the demo arrays. */
  brand?: string | null;
  /** Per-place coffee rating (1–10) aggregated from user coffee reviews.
   *  Null until at least one user submits a coffee-rated review. See #85. */
  coffee_rating?: number | null;
  /** Number of user reviews that included a coffee_quality_rating. The
   *  "Known for their coffee · X.X" stat renders when this is ≥ 1. */
  coffee_review_count?: number;
}

export const PARIS_DEMO_PLACES: DemoPlace[] = [
  {
    id: 'ten-belles',
    name: 'Ten Belles',
    address: '10 Rue de la Grange aux Belles',
    neighborhood: '10e',
    category: 'cafe',
    lat: 48.8721,
    lng: 2.3671,
    rating: 4.5,
    review_count: 0,
    avg_spend_eur: 6,
    wifi: 'fast',
    noise: 'moderate',
    outlets: 'some',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 2,
    right_now_noise: 'Usually moderate at this hour',
    right_now_seating: 'Some seats (12 min ago)',
  },
  {
    id: 'anticafe-louvre',
    name: 'Anticafé Louvre',
    address: '10 Rue de Richelieu',
    neighborhood: '1er',
    category: 'coworking',
    lat: 48.8635,
    lng: 2.3369,
    rating: 4.3,
    review_count: 0,
    avg_spend_eur: 9,
    wifi: 'fast',
    noise: 'quiet',
    outlets: 'many',
    seats: 'plenty',
    lighting: 'good',
    tabletime_hours: 8,
    right_now_noise: 'Usually quiet — good for deep work',
    right_now_seating: 'Plenty of seats (4 min ago)',
  },
  {
    id: 'bnf-mitterrand',
    name: 'BnF François-Mitterrand',
    address: 'Quai François Mauriac',
    neighborhood: '13e',
    category: 'library',
    lat: 48.8338,
    lng: 2.3764,
    rating: 4.6,
    review_count: 0,
    avg_spend_eur: 0,
    wifi: 'moderate',
    noise: 'quiet',
    outlets: 'many',
    seats: 'plenty',
    lighting: 'good',
    tabletime_hours: 10,
    right_now_noise: 'Silent reading rooms',
    right_now_seating: 'Plenty of seats',
  },
  {
    id: 'du-pain-et-des-idees',
    name: 'Du Pain et des Idées',
    address: '34 Rue Yves Toudic',
    neighborhood: '10e',
    category: 'bakery',
    lat: 48.8702,
    lng: 2.3614,
    rating: 4.7,
    review_count: 0,
    avg_spend_eur: 5,
    wifi: 'slow',
    noise: 'loud',
    outlets: 'none',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 1,
    right_now_noise: 'Busy morning rush',
    right_now_seating: 'Few seats — mostly takeaway',
  },
  {
    id: 'hoxton-paris',
    name: 'The Hoxton Paris',
    address: '30-32 Rue du Sentier',
    neighborhood: '2e',
    category: 'hotel',
    lat: 48.8692,
    lng: 2.3479,
    rating: 4.4,
    review_count: 0,
    avg_spend_eur: 8,
    wifi: 'fast',
    noise: 'moderate',
    outlets: 'some',
    seats: 'plenty',
    lighting: 'dim',
    tabletime_hours: 4,
    right_now_noise: 'Ambient lobby chatter',
    right_now_seating: 'Plenty of seats (just now)',
  },
  {
    id: 'holybelly-5',
    name: 'Holybelly 5',
    address: '5 Rue Lucien Sampaix',
    neighborhood: '10e',
    category: 'restaurant',
    lat: 48.8728,
    lng: 2.3605,
    rating: 4.5,
    review_count: 0,
    avg_spend_eur: 18,
    wifi: 'moderate',
    noise: 'loud',
    outlets: 'none',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 1,
    right_now_noise: 'Brunch crowd — loud',
    right_now_seating: 'Wait list ~20 min',
  },
  {
    id: 'boot-cafe',
    name: 'Boot Café',
    address: '19 Rue du Pont aux Choux',
    neighborhood: '3e',
    category: 'cafe',
    lat: 48.8604,
    lng: 2.3658,
    rating: 4.4,
    review_count: 0,
    avg_spend_eur: 5,
    wifi: 'moderate',
    noise: 'quiet',
    outlets: 'none',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 1,
    right_now_noise: 'Tiny space — intimate',
    right_now_seating: 'Some seats (8 min ago)',
  },
  {
    id: 'telescope',
    name: 'Télescope',
    address: '5 Rue Villedo',
    neighborhood: '1er',
    category: 'cafe',
    lat: 48.8664,
    lng: 2.3367,
    rating: 4.5,
    review_count: 0,
    avg_spend_eur: 5,
    wifi: 'fast',
    noise: 'quiet',
    outlets: 'some',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 2,
    right_now_noise: 'Calm — specialty coffee focus',
    right_now_seating: 'Some seats (just now)',
  },
  {
    id: 'shakespeare-and-co',
    name: 'Shakespeare and Company Café',
    address: '37 Rue de la Bûcherie',
    neighborhood: '5e',
    category: 'cafe',
    lat: 48.8527,
    lng: 2.3471,
    rating: 4.3,
    review_count: 0,
    avg_spend_eur: 8,
    wifi: 'slow',
    noise: 'moderate',
    outlets: 'some',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 2,
    right_now_noise: 'Tourists + laptop folks',
    right_now_seating: 'Some seats (just now)',
  },
  {
    id: 'bibliotheque-sainte-genevieve',
    name: 'Bibliothèque Sainte-Geneviève',
    address: '10 Pl. du Panthéon',
    neighborhood: '5e',
    category: 'library',
    lat: 48.8468,
    lng: 2.345,
    rating: 4.7,
    review_count: 0,
    avg_spend_eur: 0,
    wifi: 'moderate',
    noise: 'quiet',
    outlets: 'many',
    seats: 'plenty',
    lighting: 'good',
    tabletime_hours: 8,
    right_now_noise: 'Grand reading hall — library silent',
    right_now_seating: 'Plenty of seats',
  },
  {
    id: 'hexagone-cafe',
    name: 'Hexagone Café',
    address: '121 Rue du Château',
    neighborhood: '14e',
    category: 'cafe',
    lat: 48.8343,
    lng: 2.3172,
    rating: 4.6,
    review_count: 0,
    avg_spend_eur: 6,
    wifi: 'fast',
    noise: 'quiet',
    outlets: 'many',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 3,
    right_now_noise: 'Low hum of keyboards',
    right_now_seating: 'Some seats',
  },
  {
    id: 'remix-coworking',
    name: 'Remix Coworking',
    address: '20 Rue du Sentier',
    neighborhood: '2e',
    category: 'coworking',
    lat: 48.868,
    lng: 2.3475,
    rating: 4.4,
    review_count: 0,
    avg_spend_eur: 12,
    wifi: 'fast',
    noise: 'quiet',
    outlets: 'many',
    seats: 'plenty',
    lighting: 'good',
    tabletime_hours: 10,
    right_now_noise: 'Focus floor — heads down',
    right_now_seating: 'Plenty of desks',
  },
  {
    id: 'terres-de-cafe-pyramides',
    name: 'Terres de Café',
    address: '14 Rue Saint-Antoine',
    neighborhood: '4e',
    category: 'cafe',
    lat: 48.8538,
    lng: 2.3621,
    rating: 4.5,
    review_count: 0,
    avg_spend_eur: 6,
    wifi: 'moderate',
    noise: 'moderate',
    outlets: 'some',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 2,
    right_now_noise: 'Espresso machine punctuates the room',
    right_now_seating: 'Some seats',
  },
  {
    id: 'poilane-cherche-midi',
    name: 'Poilâne',
    address: '8 Rue du Cherche-Midi',
    neighborhood: '6e',
    category: 'bakery',
    lat: 48.8525,
    lng: 2.3285,
    rating: 4.8,
    review_count: 0,
    avg_spend_eur: 7,
    wifi: 'slow',
    noise: 'loud',
    outlets: 'none',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 1,
    right_now_noise: 'Bread line chatter',
    right_now_seating: 'Few — mostly takeaway',
  },
  {
    id: 'le-procope',
    name: 'Le Procope',
    address: '13 Rue de l\u2019Ancienne Comédie',
    neighborhood: '6e',
    category: 'restaurant',
    lat: 48.8535,
    lng: 2.3388,
    rating: 4.2,
    review_count: 0,
    avg_spend_eur: 35,
    wifi: 'moderate',
    noise: 'moderate',
    outlets: 'none',
    seats: 'plenty',
    lighting: 'dim',
    tabletime_hours: 2,
    right_now_noise: 'Historic wood-panel dining',
    right_now_seating: 'Plenty mid-afternoon',
  },
];

