import type { DemoPlace } from '@/lib/demo/paris-places';

export const TORONTO_DEMO_PLACES: DemoPlace[] = [
  {
    id: 'boxcar-social-harbourfront',
    name: 'Boxcar Social Harbourfront',
    address: '235 Queens Quay W',
    neighborhood: 'Harbourfront',
    category: 'cafe',
    lat: 43.6384,
    lng: -79.3833,
    rating: 4.6,
    review_count: 640,
    avg_spend_eur: 8,
    wifi: 'fast',
    noise: 'moderate',
    outlets: 'some',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 3,
    right_now_noise: 'Lakeside brunch buzz',
    right_now_seating: 'Some seats (5 min ago)',
  },
  {
    id: 'de-mello-yonge',
    name: 'De Mello Coffee',
    address: '1236 Yonge St',
    neighborhood: 'Rosedale',
    category: 'cafe',
    lat: 43.6795,
    lng: -79.3918,
    rating: 4.7,
    review_count: 820,
    avg_spend_eur: 6,
    wifi: 'fast',
    noise: 'quiet',
    outlets: 'some',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 3,
    right_now_noise: 'Calm mid-morning',
    right_now_seating: 'Some seats',
  },
  {
    id: 'toronto-reference-library',
    name: 'Toronto Reference Library',
    address: '789 Yonge St',
    neighborhood: 'Yorkville',
    category: 'library',
    lat: 43.6717,
    lng: -79.3860,
    rating: 4.8,
    review_count: 2200,
    avg_spend_eur: 0,
    wifi: 'moderate',
    noise: 'quiet',
    outlets: 'many',
    seats: 'plenty',
    lighting: 'good',
    tabletime_hours: 10,
    right_now_noise: 'Cathedral quiet',
    right_now_seating: 'Plenty of study carrels',
  },
  {
    id: 'balzacs-distillery',
    name: "Balzac's Coffee Roasters",
    address: '1 Trinity St',
    neighborhood: 'Distillery',
    category: 'cafe',
    lat: 43.6503,
    lng: -79.3599,
    rating: 4.5,
    review_count: 980,
    avg_spend_eur: 7,
    wifi: 'moderate',
    noise: 'moderate',
    outlets: 'some',
    seats: 'plenty',
    lighting: 'good',
    tabletime_hours: 3,
    right_now_noise: 'Open-loft hum',
    right_now_seating: 'Plenty of seats',
  },
  {
    id: 'workhaus-king',
    name: 'WorkHaus',
    address: '99 Yorkville Ave',
    neighborhood: 'Yorkville',
    category: 'coworking',
    lat: 43.671,
    lng: -79.391,
    rating: 4.3,
    review_count: 310,
    avg_spend_eur: 18,
    wifi: 'fast',
    noise: 'quiet',
    outlets: 'many',
    seats: 'plenty',
    lighting: 'good',
    tabletime_hours: 10,
    right_now_noise: 'Quiet — focus floor',
    right_now_seating: 'Plenty of desks',
  },
  {
    id: 'pilot-coffee-te-aro',
    name: 'Pilot Coffee Te Aro',
    address: '983 Queen St E',
    neighborhood: 'Leslieville',
    category: 'cafe',
    lat: 43.6609,
    lng: -79.3352,
    rating: 4.6,
    review_count: 720,
    avg_spend_eur: 6,
    wifi: 'fast',
    noise: 'moderate',
    outlets: 'some',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 2,
    right_now_noise: 'Steady espresso rhythm',
    right_now_seating: 'Some seats',
  },
  {
    id: 'hotel-drake',
    name: 'The Drake Hotel',
    address: '1150 Queen St W',
    neighborhood: 'Parkdale',
    category: 'hotel',
    lat: 43.6432,
    lng: -79.4254,
    rating: 4.2,
    review_count: 480,
    avg_spend_eur: 14,
    wifi: 'fast',
    noise: 'moderate',
    outlets: 'some',
    seats: 'plenty',
    lighting: 'dim',
    tabletime_hours: 4,
    right_now_noise: 'Lounge playlist',
    right_now_seating: 'Plenty',
  },
  {
    id: 'nadege-patisserie-trinity',
    name: 'Nadège Pâtisserie',
    address: '780 Queen St W',
    neighborhood: 'Trinity Bellwoods',
    category: 'bakery',
    lat: 43.6473,
    lng: -79.4132,
    rating: 4.5,
    review_count: 1100,
    avg_spend_eur: 8,
    wifi: 'slow',
    noise: 'loud',
    outlets: 'none',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 1,
    right_now_noise: 'Weekend rush',
    right_now_seating: 'Limited — mostly takeaway',
  },
  {
    id: 'fahrenheit-coffee',
    name: 'Fahrenheit Coffee',
    address: '120 Lombard St',
    neighborhood: 'St. Lawrence',
    category: 'cafe',
    lat: 43.6505,
    lng: -79.3745,
    rating: 4.6,
    review_count: 520,
    avg_spend_eur: 5,
    wifi: 'fast',
    noise: 'quiet',
    outlets: 'some',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 2,
    right_now_noise: 'Hushed morning',
    right_now_seating: 'Some seats',
  },
  {
    id: 'ihop-annex',
    name: 'Sam James Coffee Bar',
    address: '297 Harbord St',
    neighborhood: 'Annex',
    category: 'cafe',
    lat: 43.6649,
    lng: -79.4108,
    rating: 4.6,
    review_count: 670,
    avg_spend_eur: 5,
    wifi: 'moderate',
    noise: 'moderate',
    outlets: 'none',
    seats: 'some',
    lighting: 'good',
    tabletime_hours: 2,
    right_now_noise: 'Student regulars chatting',
    right_now_seating: 'Some seats',
  },
  {
    id: 'lighthouse-immigrants',
    name: 'Lighthouse Immigrant Services Library',
    address: '5100 Yonge St',
    neighborhood: 'North York',
    category: 'library',
    lat: 43.7684,
    lng: -79.4114,
    rating: 4.4,
    review_count: 290,
    avg_spend_eur: 0,
    wifi: 'fast',
    noise: 'quiet',
    outlets: 'many',
    seats: 'plenty',
    lighting: 'good',
    tabletime_hours: 8,
    right_now_noise: 'Suburban library calm',
    right_now_seating: 'Plenty',
  },
  {
    id: 'gladstone-hotel',
    name: 'Gladstone House',
    address: '1214 Queen St W',
    neighborhood: 'West Queen West',
    category: 'hotel',
    lat: 43.6423,
    lng: -79.4275,
    rating: 4.3,
    review_count: 340,
    avg_spend_eur: 12,
    wifi: 'fast',
    noise: 'moderate',
    outlets: 'some',
    seats: 'plenty',
    lighting: 'dim',
    tabletime_hours: 4,
    right_now_noise: 'Lobby chatter',
    right_now_seating: 'Plenty',
  },
];

